# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b1cccc7fc5d9b7e3bcf21652ae836659b45c9f0e3d5d14c75f021a6ecf59ee6dbbf4c927257eec8cfc73d1587dc02191d06793a507d42d2685f15ec8a871b360

test:
  secret_key_base: e1500819194d2a4b7e68abd900851654ec94b54c579b550536df1c25ee7fc7de7014d5223fc9ea8b56886b1d4814e9671bfc2aedb42b6e27c0882d459e3c54fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
